laravel/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

use JonnyW\PhantomJs\Client;

Route::group(['prefix' => 'admin'], function() {

	Route::get('/', function() {
		return redirect('admin/summary');
	});

	Route::controllers([
		'auth'		=> 'Admin\Auth\AuthController',
		'password'	=> 'Admin\Auth\PasswordController',
	]);

	Route::resource('users', 'Admin\Users\UserController');

	/* Case Study Route */
	Route::resource('case-study', 'Admin\CaseStudy\CaseStudyController');

	// Route::get(
	// 	'case-study/preview/{hash}',
	// 	array(
	// 		 'as'	=> 'case-study-preview.{hash}'
	// 		,'uses'	=> 'Admin\CaseStudy\CaseStudyController@preview'
	// 	)
	// );

	Route::post(
		'case-study/generate-slug',
		array(
			 'as'	=> 'case-study-generate-slug'
			,'uses'	=> 'Admin\CaseStudy\CaseStudyController@generateSlug'
		)
	);

	Route::post(
		'case-study/add-section',
		array(
			 'as'	=> 'case-study-add-section'
			,'uses'	=> 'Admin\CaseStudy\CaseStudyController@addSection'
		)
	);
	Route::post(
		'case-study/delete-section',
		array(
			'as'	=> 'case-study-delete-section'
			,'uses'	=> 'Admin\CaseStudy\CaseStudyController@deleteSection'
		)
	);
	Route::post(
		'case-study/update-order/{id}',
		array(
			 'as'	=> 'case-study-update-order.{id}'
			,'uses'	=> 'Admin\CaseStudy\CaseStudyController@updateOrder'
		)
	);
	Route::post(
		'case-study/update-order-ident',
		array(
			 'as'	=> 'case-study-update-order'
			,'uses'	=> 'Admin\CaseStudy\CaseStudyController@updateOrderIdent'
		)
	);
	Route::post(
		'case-study/edit-status',
		array(
			 'as'	=> 'case-study-edit-status'
			,'uses'	=> 'Admin\CaseStudy\CaseStudyController@editStatus'
		)
	);

	// HEADER ROUTE
	Route::get(
		'case-study/edit-header/{id}',
		array(
			'as'	=> 'case-study-edit-header.{id}'
			,'uses'	=> 'Admin\CaseStudy\CaseStudyController@editHeader'
		)
	);
	Route::put(
		'case-study/update-header/{id}',
		array(
			 'as'	=> 'case-study-update-header.{id}'
			,'uses'	=> 'Admin\CaseStudy\CaseStudyController@updateHeader'
		)
	);

	// STATISTICS ROUTE
	Route::get(
		'case-study/edit-statistics/{id}',
		array(
			'as'	=> 'case-study-edit-statistics.{id}'
			,'uses'	=> 'Admin\CaseStudy\CaseStudyController@editStatistics'
		)
	);
	Route::put(
		'case-study/update-statistics/{id}',
		array(
			 'as'	=> 'case-study-update-statistics.{id}'
			,'uses'	=> 'Admin\CaseStudy\CaseStudyController@updateStatistics'
		)
	);

	// TEXT AREA ROUTE
	Route::get(
		'case-study/edit-textarea/{cid}/{sid}',
		array(
			 'as'	=> 'case-study-edit-textarea.{cid}.{sid}'
			,'uses'	=> 'Admin\CaseStudy\CaseStudyController@editTextArea'
		)
	);
	Route::put(
		'case-study/update-textarea/{cid}/{sid}',
		array(
			 'as'	=> 'case-study-edit-textarea-update.{cid}.{sid}'
			,'uses'	=> 'Admin\CaseStudy\CaseStudyController@updateTextArea'
		)
	);

	// PARALLAX ROUTE
	Route::get(
		'case-study/edit-parallax/{cid}/{sid}',
		array(
			 'as'	=> 'case-study-edit-parallax.{cid}.{sid}'
			,'uses'	=> 'Admin\CaseStudy\CaseStudyController@editParallax'
		)
	);
	Route::put(
		'case-study/update-parallax/{cid}/{sid}',
		array(
			 'as'	=> 'case-study-update-parallax.{cid}.{sid}'
			,'uses'	=> 'Admin\CaseStudy\CaseStudyController@updateParallax'
		)
	);

	// SLIDER ROUTE
	Route::get(
		'case-study/edit-slider/{cid}/{sid}',
		array(
			 'as'	=> 'case-study-edit-slider.{cid}.{sid}'
			,'uses'	=> 'Admin\CaseStudy\CaseStudyController@editSlider'
		)
	);
	Route::put(
		'case-study/update-slider/{cid}/{sid}',
		array(
			'as'	=> 'case-study-update-slider.{cid}.{sid}'
			,'uses'	=> 'Admin\CaseStudy\CaseStudyController@updateSlider'
		)
	);

	// VIDEO ROUTE
	Route::get(
		'case-study/edit-video/{cid}/{sid}',
		array(
			 'as'	=> 'case-study-edit-video.{cid}.{sid}'
			,'uses'	=> 'Admin\CaseStudy\CaseStudyController@editVideo'
		)
	);
	Route::put(
		'case-study/update-video/{cid}/{sid}',
		array(
			'as'	=> 'case-study-update-video.{cid}.{sid}'
			,'uses'	=> 'Admin\CaseStudy\CaseStudyController@updateVideo'
		)
	);

	// CAROUSEL ROUTE
	Route::get(
		'case-study/edit-carousel/{cid}/{sid}',
		array(
			 'as'	=> 'case-study-edit-carousel.{cid}.{sid}'
			,'uses'	=> 'Admin\CaseStudy\CaseStudyController@editCarousel'
		)
	);

	Route::post(
		'case-study/add-carousel-image',
		array(
			 'as'	=> 'case-study-add-carousel.{cid}.{sid}'
			,'uses'	=> 'Admin\CaseStudy\CaseStudyController@addCarousel'
		)
	);

	Route::post(
		'case-study/update-theme',
		array(
			 'as'	=> 'update-theme.{cid}.{sid}'
			,'uses'	=> 'Admin\CaseStudy\CaseStudyController@updateTheme'
		)
	);

	Route::put(
		'case-study/update-carousel-image/{cid}/{sid}',
		array(
			 'as'	=> 'case-study-update-carousel.{cid}.{sid}'
			,'uses'	=> 'Admin\CaseStudy\CaseStudyController@updateCarousel'
		)
	);

	Route::post(
		'case-study/update-carousel-order',
		array(
			 'as'	=> 'case-study-update-carousel-order'
			,'uses'	=> 'Admin\CaseStudy\CaseStudyController@updateCarouselOrder'
		)
	);

	Route::post(
		'case-study/delete-carousel-section',
		array(
			 'as'	=> 'case-study-delete-carousel-section'
			,'uses'	=> 'Admin\CaseStudy\CaseStudyController@deleteCarouseSectionCarousel'
		)
	);


	Route::get('summary', 'Admin\Summary\SummaryController@index');

	Route::group(['prefix' => 'social'], function() {

		Route::get('twitter', 'Admin\Social\TwitterController@index');
		Route::post('twitter/disable/{id}', 'Admin\Social\TwitterController@disable');
		Route::post('twitter/enable/{id}', 'Admin\Social\TwitterController@enable');
		Route::delete('twitter/destroy/{id}', 'Admin\Social\TwitterController@destroy');

		Route::get('vimeo', 'Admin\Social\VimeoController@index');
		Route::post('vimeo/store', 'Admin\Social\VimeoController@store');
		Route::post('vimeo/disable/{id}', 'Admin\Social\VimeoController@disable');
		Route::post('vimeo/enable/{id}', 'Admin\Social\VimeoController@enable');
		Route::delete('vimeo/destroy/{id}', 'Admin\Social\VimeoController@destroy');

		Route::get('linkedin', 'Admin\Social\LinkedInController@index');
		Route::get('linkedin/create', 'Admin\Social\LinkedInController@create');
		Route::post('linkedin/store', 'Admin\Social\LinkedInController@store');
		Route::post('linkedin/disable/{id}', 'Admin\Social\LinkedInController@disable');
		Route::post('linkedin/enable/{id}', 'Admin\Social\LinkedInController@enable');
		Route::delete('linkedin/destroy/{id}', 'Admin\Social\LinkedInController@destroy');

		Route::get('pinterest', 'Admin\Social\PinterestController@index');
		Route::post('pinterest/store', 'Admin\Social\PinterestController@store');
		Route::post('pinterest/disable/{id}', 'Admin\Social\PinterestController@disable');
		Route::post('pinterest/enable/{id}', 'Admin\Social\PinterestController@enable');
		Route::delete('pinterest/destroy/{id}', 'Admin\Social\PinterestController@destroy');

		Route::get('potm', 'Admin\Social\PotmController@index');
		Route::get('potm/create', 'Admin\Social\PotmController@create');
		Route::post('potm/store', 'Admin\Social\PotmController@store');
		Route::post('potm/disable/{id}', 'Admin\Social\PotmController@disable');
		Route::post('potm/enable/{id}', 'Admin\Social\PotmController@enable');
		Route::delete('potm/destroy/{id}', 'Admin\Social\PotmController@destroy');

		Route::get('images', 'Admin\Social\ImagesController@index');
		Route::get('images/create', 'Admin\Social\ImagesController@create');
		Route::post('images/store', 'Admin\Social\ImagesController@store');
		Route::post('images/disable/{id}', 'Admin\Social\ImagesController@disable');
		Route::post('images/enable/{id}', 'Admin\Social\ImagesController@enable');
		Route::delete('images/destroy/{id}', 'Admin\Social\ImagesController@destroy');
	});
});

Route::get('/', 'Main\HomeController@index');

Route::get('/cui', 'Main\ConversationUIController@index');
Route::get('/cui/upload-csv', 'Main\ExcelUploadController@index');
Route::get('/cui/{source}', 'Main\ConversationUIController@index');
Route::get('/cui/get-next-line/{id}', 'Main\ConversationUIController@getNextLine'); // CREATE SOCIAL MEDIA END POINTS

Route::get('/projects',				'Main\Projects\ProjectsController@index');
Route::get('/projects/{casestudy}', 'Main\Projects\ProjectsController@view');
Route::get('/css/cms_style/{id}', 'Main\Projects\CmsCssController@index');
Route::get(
	'projects/preview/{hash}',
	array(
		 'as'		=> 'case-study-preview.{hash}'
		,'uses'	=> 'Main\Projects\ProjectsController@preview'
	)
);
// SCREEN CAPTURE
Route::get('/screenshot', function() {

	$url = Input::get('url');
	$width  = 1280;
  $height = 6000;

	$client = Client::getInstance();
	$client->getEngine()->setPath(dirname(dirname(__FILE__)).'../../bin/phantomjs.exe');
	$client->isLazy();

  $request  = $client->getMessageFactory()->createCaptureRequest($url);
	$request->setViewportSize($width, $height);
	$file = '../bin/file.jpg';
	$request->setOutputFile($file);
	$request->setTimeout(30000);

  $response = $client->getMessageFactory()->createResponse();

  $client->send($request, $response);

	rename('../bin/file.jpg', 'screenshots/file.jpg');

	echo '<img src="screenshots/file.jpg" />';
});

Route::get('/services',							'Main\Services\ServicesController@index');
Route::get('/services/presentation-solutions',	'Main\Services\ServicesController@presentations');
Route::get('/services/digital-solutions',		'Main\Services\ServicesController@digital');
Route::get('/services/digital',					function(){
	return redirect('/services/digital-solutions');
});
Route::get('/services/information-security',	'Main\Services\ServicesController@infosec');
Route::get('/services/video-animation-3d',		'Main\Services\ServicesController@motion');

laravel/resources/views/admin/casestudy/create.blade.php
@extends('admin.layouts.main')

@section('content')

	@include('admin.layouts.partials.header')

	<div class="row">
		<div class="small-12 columns">
			<ul class="breadcrumbs">
			  <li>{!! link_to_route('admin.case-study.index', 'Case Study') !!}</li>
			  <li class="current">Create Case Study</li>
			</ul>

			{!! Form::open(array('route' => ['admin.case-study.store'], 'method' => 'POST') )!!}
				<div class="row">
					<div class="small-12 columns mt1">
						@include('admin.casestudy.partials._create_form')
					</div>
				</div>
				<div class="row">
					<div class="small-12 columns">
						{!! Form::submit('Create', array('class' => 'button success small ff')) !!}
						{!! link_to_route('admin.case-study.index', 'Cancel', [], ['class' => 'small button alert ff']) !!}
					</div>
				</div>
			{!! Form::close() !!}
		</div>
	</div>
@stop

laravel/resources/views/admin/casestudy/edit_carousel_block.blade.php
@extends('admin.layouts.main')

@section('content')

	@include('admin.layouts.partials.header')

	<div class="row">
		<div class="small-12 columns">

			<ul class="breadcrumbs">
			  <li>{!! link_to_route('admin.case-study.index', 'Case Study List') !!}</li>
			  <li>{!! link_to_route('admin.case-study.edit', 'Edit '.$cms_case_study->casestudy_title.' Layout',  [$cms_case_study->id]) !!}</li>
			  <li class="current">Edit {{ $cms_case_study->casestudy_title }} Carousel Block</li>
			</ul>

			<div id="carousel_wrap" class="row">
				<!-- TOP ADD BUTTON -->
				<div class="small-12 columns">
					{!! link_to_route('admin.case-study.edit', '', [$cms_case_study->id], ['class' => 'small button warning ff icon3-angle-left thin']) !!}
					<button class="button small button success ff" @click="addCarousel">Add Panel</button>
				</div>

				<div class="small-12 columns theme">
					<h4>Theme</h4>
					<input type="checkbox" id="light" class="checkbox-style" value="light" @click="chooseTheme($event, true)">
					<label for="light" data-id="light"></label>
					<span class="noselect">Light</span>
					<input type="checkbox" id="dark" class="checkbox-style" value="dark" @click="chooseTheme($event, true)">
					<label for="dark" data-id=""></label>
					<span class="noselect">Dark</span>
					<transition
						@before-enter="beforeEnter"
						@enter="enter"
						@before-leave="beforeLeave"
						@leave="leave"
						v-bind:css="false">
						<span v-cloak v-if="themeSaved" class="success label theme-state">theme saved</span>
					</transition>
				</div>

				<div class="small-12 columns">
				{!! Form::model($cms_Carousel, array('route' => ['case-study-update-carousel.{cid}.{sid}', $cms_case_study->id, $cms_Carousel->first()->id], 'method' => 'PUT', 'files' => true) )!!}
					<input type="hidden" name="carousel_csid" value="{{$cms_Carousel->first()->csid}}">
					<input type="hidden" name="carousel_count" :value="carouselNum">
					@include('admin.casestudy.partials._edit_carousel_form')
					<!-- BOTTOM ADD BUTTON -->
					<!-- <div class="small-12 columns"> -->
					{!! link_to_route('admin.case-study.edit', '', [$cms_case_study->id], ['class' => 'small button warning ff icon3-angle-left thin']) !!}
					<button class="button small button success ff" @click="addCarousel">Add Panel</button>
					<!-- </div> -->
					{!! Form::submit('Upload', array('class' => 'button success small')) !!}
					{!! link_to_route('admin.case-study.edit', 'Cancel', [$cms_case_study->id], ['class' => 'small button alert ff']) !!}
				{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
	@include('admin.casestudy.partials._vue_templates')
@stop

laravel/resources/views/admin/casestudy/edit_header.blade.php
@extends('admin.layouts.main')

@section('content')

	@include('admin.layouts.partials.header')

	<div class="row">
		<div id="header_wrap" class="small-12 columns">

			<ul class="breadcrumbs">
			  <li>{!! link_to_route('admin.case-study.index', 'Case Study List') !!}</li>
			  <li>{!! link_to_route('admin.case-study.edit', 'Edit '.$cms_case_study->casestudy_title.' Layout',  [$cms_case_study->id]) !!}</li>
			  <li class="current">Edit {{ $cms_case_study->casestudy_title }} Header</li>
			</ul>


			<!-- TOP ADD BUTTON -->
			{!! link_to_route('admin.case-study.edit', '', [$cms_case_study->id], ['class' => 'small button warning ff icon3-angle-left thin']) !!}
			<button data-dropdown="top_drop_001" aria-controls="top_drop_001" aria-expanded="false" class="button small button success ff dropdown">Header Type</button>
			<ul id="top_drop_001" data-dropdown-content class="f-dropdown" aria-hidden="true">
				<li><a href="#" data-type="text" @click="showImageImput">Image</a></li>
				<li><a href="#" data-type="parallax" @click="showVideoImput">Video</a></li>
			</ul>

			{!! Form::model($cms_case_study, array('route' => ['case-study-update-header.{id}', $cms_case_study->id], 'method' => 'PUT', 'files' => true) )!!}
				<input type="hidden" name="header_image_active" :value="showImage">
				<div class="row">
					<div class="small-12 columns mt1">
						@include('admin.casestudy.partials._edit_header_form')
					</div>
				</div>
				<div class="row">
					<div class="small-12 columns">
						{!! link_to_route('admin.case-study.edit', '', [$cms_case_study->id], ['class' => 'small button warning ff icon3-angle-left thin']) !!}
						{!! Form::submit('Update', array('class' => 'button success small')) !!}
						{!! link_to_route('admin.case-study.edit', 'Cancel', [$cms_case_study->id], ['class' => 'small button alert ff']) !!}
					</div>
				</div>
			{!! Form::close() !!}
		</div>
	</div>
@stop

laravel/resources/views/admin/casestudy/edit_parallax_block.blade.php
@extends('admin.layouts.main')

@section('content')

	@include('admin.layouts.partials.header')

	<div class="row">
		<div class="small-12 columns">

			<ul class="breadcrumbs">
			  <li>{!! link_to_route('admin.case-study.index', 'Case Study List') !!}</li>
			  <li>{!! link_to_route('admin.case-study.edit', 'Edit '.$cms_case_study->casestudy_title.' Layout',  [$cms_case_study->id]) !!}</li>
			  <li class="current">Edit {{ $cms_case_study->casestudy_title }} Parallax Image</li>
			</ul>

			<!-- TOP ADD BUTTON -->
			{!! link_to_route('admin.case-study.edit', '', [$cms_case_study->id], ['class' => 'small button warning ff icon3-angle-left thin']) !!}

			{!! Form::model($cms_Parallax, array('route' => ['case-study-update-parallax.{cid}.{sid}', $cms_case_study->id, $cms_Parallax->id], 'method' => 'PUT', 'files' => true) )!!}
				<div class="row">
					<div class="small-12 columns mt1">
						@include('admin.casestudy.partials._edit_parallax_form')
					</div>
				</div>
				<div class="row cms-update-button-wrap">
					<div class="small-12 columns">
						{!! link_to_route('admin.case-study.edit', '', [$cms_case_study->id], ['class' => 'small button warning ff icon3-angle-left thin']) !!}
						{!! Form::submit('Upload', array('class' => 'button success small')) !!}
						{!! link_to_route('admin.case-study.edit', 'Cancel', [$cms_case_study->id], ['class' => 'small button alert ff']) !!}
					</div>
				</div>
			{!! Form::close() !!}
		</div>
	</div>
@stop

laravel/resources/views/admin/casestudy/edit_slider_block.blade.php
@extends('admin.layouts.main')

@section('content')

	@include('admin.layouts.partials.header')

	<div class="row">
		<div class="small-12 columns">

			<ul class="breadcrumbs">
			  <li>{!! link_to_route('admin.case-study.index', 'Case Study List') !!}</li>
			  <li>{!! link_to_route('admin.case-study.edit', 'Edit '.$cms_case_study->casestudy_title.' Layout',  [$cms_case_study->id]) !!}</li>
			  <li class="current">Edit {{ $cms_case_study->casestudy_title }} Slider Block</li>
			</ul>

			<!-- TOP ADD BUTTON -->
			{!! link_to_route('admin.case-study.edit', '', [$cms_case_study->id], ['class' => 'small button warning ff icon3-angle-left thin']) !!}

			{!! Form::model($cms_case_study, array('route' => ['case-study-update-slider.{cid}.{sid}', $cms_case_study->id, $cms_Slide->id], 'method' => 'PUT', 'files' => true) )!!}
				<div class="row">
					<div class="small-12 columns mt1">
						@include('admin.casestudy.partials._edit_slider_form')
					</div>
				</div>
				<div class="row">
					<div class="small-12 columns">
						{!! link_to_route('admin.case-study.edit', '', [$cms_case_study->id], ['class' => 'small button warning ff icon3-angle-left thin']) !!}
						{!! Form::submit('Upload', array('class' => 'button success small')) !!}
						{!! link_to_route('admin.case-study.edit', 'Cancel', [$cms_case_study->id], ['class' => 'small button alert ff']) !!}
					</div>
				</div>
			{!! Form::close() !!}
		</div>
	</div>
@stop

laravel/resources/views/admin/casestudy/edit_statistics.blade.php
@extends('admin.layouts.main')

@section('content')

	@include('admin.layouts.partials.header')

	<div class="row">
		<div class="small-12 columns">

			<ul class="breadcrumbs">
			  <li>{!! link_to_route('admin.case-study.index', 'Case Study List') !!}</li>
			  <li>{!! link_to_route('admin.case-study.edit', 'Edit '.$cms_case_study->casestudy_title.' Layout',  [$cms_case_study->id]) !!}</li>
			  <li class="current">Edit {{ $cms_case_study->casestudy_title }} Statistics</li>
			</ul>

			<!-- TOP ADD BUTTON -->
			{!! link_to_route('admin.case-study.edit', '', [$cms_case_study->id], ['class' => 'small button warning ff icon3-angle-left thin']) !!}

			{!! Form::model($cms_case_study, array('route' => ['case-study-update-statistics.{id}', $cms_case_study->id], 'method' => 'PUT', 'files' => true) )!!}
				<div class="row">
					<div class="small-12 columns mt1">
						@include('admin.casestudy.partials._edit_statistics_form')
					</div>
				</div>
				<div class="row">
					<div class="small-12 columns">
						{!! link_to_route('admin.case-study.edit', '', [$cms_case_study->id], ['class' => 'small button warning ff icon3-angle-left thin']) !!}
						{!! Form::submit('Upload', array('class' => 'button success small')) !!}
						{!! link_to_route('admin.case-study.edit', 'Cancel', [$cms_case_study->id], ['class' => 'small button alert ff']) !!}
					</div>
				</div>
			{!! Form::close() !!}
		</div>
	</div>
@stop

laravel/resources/views/admin/casestudy/edit_text_block.blade.php
@extends('admin.layouts.main')

@section('content')

	@include('admin.layouts.partials.header')

	<div class="row">
		<div class="small-12 columns">

			<ul class="breadcrumbs">
			  <li>{!! link_to_route('admin.case-study.index', 'Case Study List') !!}</li>
			  <li>{!! link_to_route('admin.case-study.edit', 'Edit '.$cms_case_study->casestudy_title.' Layout',  [$cms_case_study->id]) !!}</li>
			  <li class="current">Edit {{ $cms_case_study->casestudy_title }} Text Block</li>
			</ul>

			<!-- TOP ADD BUTTON -->
			{!! link_to_route('admin.case-study.edit', '', [$cms_case_study->id], ['class' => 'small button warning ff icon3-angle-left thin']) !!}

			{!! Form::model($cms_Text, array('route' => ['case-study-edit-textarea-update.{cid}.{sid}', $cms_case_study->id, $cms_Text->id], 'method' => 'PUT', 'files' => true) )!!}
				<div class="row">
					<div class="small-12 columns mt1">
						@include('admin.casestudy.partials._edit_text_form')
					</div>
				</div>
				<div class="row">
					<div class="small-12 columns">
						{!! link_to_route('admin.case-study.edit', '', [$cms_case_study->id], ['class' => 'small button warning ff icon3-angle-left thin']) !!}
						{!! Form::submit('Update', array('class' => 'button success small')) !!}
						{!! link_to_route('admin.case-study.edit', 'Cancel', [$cms_case_study->id], ['class' => 'small button alert ff']) !!}
					</div>
				</div>
			{!! Form::close() !!}
		</div>
	</div>
@stop

laravel/resources/views/admin/casestudy/edit_video_block.blade.php
@extends('admin.layouts.main')

@section('content')

	@include('admin.layouts.partials.header')

	<div class="row">
		<div class="small-12 columns">

			<ul class="breadcrumbs">
			  <li>{!! link_to_route('admin.case-study.index', 'Case Study List') !!}</li>
			  <li>{!! link_to_route('admin.case-study.edit', 'Edit '.$cms_case_study->casestudy_title.' Layout',  [$cms_case_study->id]) !!}</li>
			  <li class="current">Edit {{ $cms_case_study->casestudy_title }} Video Block</li>
			</ul>

			<!-- TOP ADD BUTTON -->
			{!! link_to_route('admin.case-study.edit', '', [$cms_case_study->id], ['class' => 'small button warning ff icon3-angle-left thin']) !!}

			{!! Form::model($cms_Video, array('route' => ['case-study-update-video.{cid}.{sid}', $cms_case_study->id, $cms_Video->id], 'method' => 'PUT', 'files' => true) )!!}
				<div class="row">
					<div class="small-12 columns mt1">
						@include('admin.casestudy.partials._edit_video_form')
					</div>
				</div>
				<div class="row">
					<div class="small-12 columns">
						{!! link_to_route('admin.case-study.edit', '', [$cms_case_study->id], ['class' => 'small button warning ff icon3-angle-left thin']) !!}
						{!! Form::submit('Update', array('class' => 'button success small')) !!}
						{!! link_to_route('admin.case-study.edit', 'Cancel', [$cms_case_study->id], ['class' => 'small button alert ff']) !!}
					</div>
				</div>
			{!! Form::close() !!}
		</div>
	</div>
@stop